[docs] Fully document the glyf table
fonttools/fonttools pull request #2457
Opened 2021-11-22 17:35 UTC by simoncozens

2021-11-22 19:26 UTC, dscorbett requested changes

2021-11-23 14:29 UTC, dscorbett requested changes

2021-11-23 14:29 UTC, dscorbett commented on Lib/fontTools/ttLib/tables/_g_l_y_f.py
> +		Raises a ``KeyError`` the glyph name is not found in the font.
“`KeyError` the glyph name” should be “`KeyError` if the glyph ID”.

2021-11-23 14:29 UTC, dscorbett commented on Lib/fontTools/ttLib/tables/_g_l_y_f.py
> +		Raises a ``KeyError`` the glyph name is not found in the font.
“`KeyError` the” should be “`ValueError` if the”.

2021-12-02 15:24 UTC, anthrotype approved these changes
thanks!

2021-12-02 15:32 UTC, merged